apiVersion: v1
kind: Service
metadata:
  name: newsfeed-cassandra-nodeport-service
spec:
  type: NodePort
  selector:
    component: newsfeed-cassandra
  ports:
    - port: 9042
      targetPort: 9042