apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newsfeed-cassandra-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: newsfeed-cassandra-persistent-volume
  storageClassName: ""